### ISSUE TITLE
Allow for recording games

### ISSUE THREAD

**Issue by Zeragamba** [step1041/Athena#9]
Our user Krusher99 would like to use our app to record his games.

To record his games, from the home page, he clicks or taps a button on the homepage. He his then presented with a simple form for entering the following information:

- His rank at the end of the game
- The outcome of the match
- a button to save the game

The record game form should be easy to use from a mobile interface. 

When Krusher99 taps the save button, the game is saved to the database, and Krusher is returned to the list of recorded games.

**Comment by Avendor7** [comment]
#28
